### ISSUE TITLE
BLAS memory regions allocations

### ISSUE THREAD

**Issue by FordUniver** [coin-or/Csdp#17]
I am currently trying to solve a problem with around 1.4 million variables and 12k constraints using CSDP.jl, but I am getting multiple `BLAS : Program is Terminated. Because you tried to allocate too many memory regions.` error messages and the solver terminates. I am not sure if this is hitting genuine hardware limitations here or if this could be resolved?

**Comment by laurentbartholdi** [comment]
I encountered similar issues with already far fewer variables. From the documentation, the memory requirement is roughly 8m^2 where m is the number of variables; so you'll need about 16 terabytes of RAM. Unless you work for the NSA, you're better off with an algorithm with lower memory footprint, such as SCS.

If you really want to use CSDP, you should modify the variable O from full array to sparse array, and change all relevant calls (DPOTRF, etc.) to their sparse equivalent.

**Comment by FordUniver** [comment]
I managed to get it to run on different hardware with 16**G**b of memory (instead of the 1Tb the previous machine had), so this doesn't seem to be about hard memory limits. Memory usage of CSDP has actually been fairly controlled on smaller versions of these types of instances, about on par with SCS (which fails to produce meaningful solutions here). I am assuming the issue lies with the BLAS installation on the machine, so I'm closing this issue.
