### ISSUE TITLE
initparams.c does not compile on msvc

### ISSUE THREAD

**Issue by seechuenteck** [coin-or/Csdp#3]
Because msvc does not have strings.h, initparams.c does not compile. The old version works fine on msvc.

**Comment by brianborchers** [comment]
strings.h is POSIX standard and available in mingw64 on Windows systems.  If getting the code to compile under msvc is important to you for some reason, then you could rewrite the routine to use only ANSI C features and contribute your version of the parser.  I don't have time to mess around with this myself.
